(() => {
'use strict';
const $=id=>document.getElementById(id),D=window.AdventureData;
const type=document.body.dataset.game||new URLSearchParams(location.search).get('game')||location.pathname.match(/memory-(train|candy|animals|differences)\.html$/)?.[1]||'train';
const names={train:'形狀列車',candy:'糖果小店',animals:'動物回家',differences:'找出變化'};
const tokens=type==='candy'?D.candies:type==='animals'?D.animals:D.shapes;
const config=[{n:3,t:[3000]},{n:4,t:[2500]},{n:5,t:[1500,2000]},{n:6,t:[750,1000,1500]},{n:8,t:[500,1000,2000]}];
let phase='idle',round=1,puzzle=[],answers=[],times=[],selected=0,sceneIndex=0,found=new Set(),hinted=new Set(),timer=null,generation=0,sound=true,audio=null,musicTimer=null,focusBeforeWin=null;
const pick=a=>a[Math.floor(Math.random()*a.length)],cfg=()=>config[Number($('level').value)-1];
function cancel(){clearTimeout(timer);timer=null;generation++;}
const differenceCount=()=>D.scenes[sceneIndex].intrinsic?D.scenes[sceneIndex].items.length:Number($('level').value)===1?5:6;
function note(){const c=cfg();$('note').textContent=type==='differences'?`${differenceCount()} 處不同 · ${Number($('level').value)<=2?'並排對照':Number($('level').value)===3?'觀察 12 秒':Number($('level').value)===4?'觀察 8 秒':'觀察 5 秒'} · ${D.scenes.length===1?'1 組修正版示例':`共 ${D.scenes.length} 組場景`}`:`${c.n} ${type==='animals'?'間小屋':'格'} · ${type==='animals'?`觀察 ${[12,10,8,6,4][Number($('level').value)-1]} 秒`: `每個停留 ${c.t.map(t=>t/1000).join('／')} 秒${c.t.length>1?'（隨機）':''}`} · 不限作答時間`;}
function tone(notes=[523,659,784],volume=.06){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});notes.forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+i*.14;o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.001,t);g.gain.linearRampToValueAtTime(volume,t+.02);g.gain.exponentialRampToValueAtTime(.001,t+.3);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.35);o.onended=()=>{o.disconnect();g.disconnect();};});}catch{}}
function stopMusic(){clearInterval(musicTimer);musicTimer=null;}
function startMusic(){stopMusic();if(sound&&!document.hidden){tone([523,659,784,659],.025);let i=0;musicTimer=setInterval(()=>{tone([[523,659],[587,698],[659,784],[523,784]][i++%4],.025);},2200);}}
function state(text){$('status').textContent=text;}
function draw(values,feedback=false,active=-1){$('slots').style.setProperty('--count',puzzle.length||cfg().n);$('slots').replaceChildren();values.forEach((v,i)=>{const b=document.createElement('button');b.className=`slot carriage-${i} ${type==='animals'?'animal-house':''} ${active===i?'active':''} ${feedback?(v===puzzle[i]?'correct':'wrong'):''}`;b.disabled=phase!=='answer'||type!=='animals';b.setAttribute('aria-label',`第 ${i+1} 格：${v===null?'空白':tokens[v].name}`);b.innerHTML=`<span class="number">${i+1}</span>${v===null?'':tokens[v].art}${feedback?`<span class="mark">${v===puzzle[i]?'✓ 記啱':'✗ 再試'}</span>`:''}`;b.onclick=()=>{if(phase!=='answer')return;answers[i]=selected;draw(answers);$('check').disabled=answers.some(v=>v===null);tone([660],.035);};$('slots').append(b);});}
function palette(){ $('palette').replaceChildren();tokens.forEach((t,i)=>{const b=document.createElement('button');b.innerHTML=t.art+t.name;b.setAttribute('aria-label',t.name);b.setAttribute('aria-pressed',String(type==='animals'&&i===selected));b.onclick=()=>{if(phase!=='answer')return;if(type==='animals'){selected=i;palette();}else{if(answers.length>=puzzle.length)return;answers.push(i);draw(puzzle.map((_,j)=>answers[j]??null));$('check').disabled=answers.length!==puzzle.length;$('undo').disabled=false;state(`已填 ${answers.length}／${puzzle.length} 格`);}tone([600],.025);};$('palette').append(b);});}
function recall(){phase='answer';answers=type==='animals'?Array(puzzle.length).fill(null):[];selected=0;draw(Array(puzzle.length).fill(null));palette();$('palette').hidden=false;$('check').hidden=false;$('check').disabled=true;$('undo').hidden=type==='animals';$('undo').disabled=true;$('start').disabled=false;state(type==='animals'?'先揀動物，再點小屋放回原位。':'按出場順序，逐個揀返圖案。');}
function observe(){cancel();const current=generation;phase='observe';$('review').hidden=true;$('retry').hidden=true;$('check').hidden=true;$('undo').hidden=true;$('palette').hidden=true;$('success').hidden=true;$('start').disabled=true;
if(type==='animals'){draw(puzzle);state('記住每隻動物住喺邊間小屋！');timer=setTimeout(()=>{if(current===generation)recall();},[12,10,8,6,4][Number($('level').value)-1]*1000);return;}
let i=0;function show(){if(current!==generation)return;if(i===puzzle.length){recall();return;}const v=Array(puzzle.length).fill(null);v[i]=puzzle[i];draw(v,false,i);state(`仔細睇：第 ${i+1}／${puzzle.length} 個`);tone([500+i*55],.025);timer=setTimeout(()=>{draw(Array(puzzle.length).fill(null));i++;timer=setTimeout(show,250);},times[i]);}show();}
function win(){phase='won';$('start').disabled=false;$('hint').hidden=true;focusBeforeWin=document.activeElement;$('winTitle').textContent=type==='differences'?'全部搵到！':'全部記啱！';$('winText').textContent=type==='differences'&&D.scenes.length===1?'六處都搵到！修正版示例完成，可以再玩一次。':'你成功過關！準備好先按「下一關」。';$('success').hidden=false;$('next').focus();tone([523,659,784,1047,784,1047],.08);if(!matchMedia('(prefers-reduced-motion: reduce)').matches)for(let i=0;i<36;i++){const s=document.createElement('span');s.className='confetti';if(document.body.dataset.art==='fairytale'){s.className+=' shape-art shape-7';}else{s.textContent=pick(['⭐','🌸','✨','🎉']);}s.style.left=Math.random()*100+'vw';s.style.animationDelay=Math.random()*.6+'s';document.body.append(s);setTimeout(()=>s.remove(),3500);}}
function check(){if(phase!=='answer')return;phase='result';$('palette').hidden=true;$('undo').hidden=true;$('check').hidden=true;draw(answers,true);const n=answers.filter((v,i)=>v===puzzle[i]).length;$('review').hidden=false;$('review').innerHTML='<strong>正確次序／位置</strong><br>'+puzzle.map((v,i)=>`<span>${i+1}. ${tokens[v].art} ${tokens[v].name}　</span>`).join('');if(n===puzzle.length){state('每一格都記啱！');win();}else{state(`記啱 ${n}／${puzzle.length} 格。睇吓正確位置，再試一次！`);$('retry').hidden=false;tone([392,440],.04);}}
const scene=()=>D.scenes[sceneIndex];
function drawScenes(hideOriginal=false){
 const s=scene(),n=differenceCount();$('pair').replaceChildren();
 [0,1].forEach(side=>{
  const outer=document.createElement('div'),label=document.createElement('p');label.className='scene-label';label.textContent=side?'變化後：點出不同位置':'原圖：仔細觀察';outer.append(label);
  const box=document.createElement('div');box.className='scene';box.style.setProperty('--zoom-origin',sceneIndex===0?'12% 36%':'50% 36%');const img=document.createElement('img');img.src=side&&s.changedImage?s.changedImage:s.image;img.alt=s.title+(side?'變化後':'原圖');box.append(img);
  box.onclick=e=>{if(e.target===img&&phase==='spot'){state('呢個位置冇變，仔細比對其他地方！');tone([392],.025);}};
  s.items.forEach((item,j)=>{
   const b=document.createElement('button');b.className=`object ${found.has(j)?'found':''} ${side&&j<n&&item.change==='missing'?'blank':''}`;b.style.left=item.x+'%';b.style.top=item.y+'%';b.setAttribute('aria-label',`${side?'變化圖':'原圖'}：${item.name}${found.has(j)?'，已找到':''}`);if(!s.intrinsic)b.innerHTML=D.object(item.type,side&&j<n?item.b:item.a);
   if(s.intrinsic){b.className=`object ${found.has(j)?'found':''}`;b.innerHTML='';b.style.width=item.w+'%';b.style.height=item.h+'%';b.setAttribute('aria-label',`${side?'變化圖':'原圖'}：位置 ${j+1}${found.has(j)?'，已找到 '+item.name:''}`);}
   b.onclick=()=>{if(phase!=='spot'||found.has(j))return;if(j>=n){state('呢個物件冇變，試吓其他位置！');tone([392],.025);return;}found.add(j);drawScenes(Number($('level').value)>=3);state(`已找到 ${found.size}／${n} 處不同：${item.name}${hinted.size?`（提示 ${hinted.size} 處）`:''}`);tone([784,1047],.035);if(found.size===n)win();};box.append(b);
  });
  if((side===0&&hideOriginal)||(side===1&&phase==='observe')){box.hidden=true;const cover=document.createElement('div');cover.className='board';cover.innerHTML=side===0?'<h2>🧠 原圖已收起</h2><p>憑記憶，搵出右圖有變化嘅物件。</p>':'<h2>✨ 變化圖片稍後揭曉</h2><p>先記住左圖嘅物件同顏色。</p>';outer.append(cover);}
  outer.append(box);$('pair').append(outer);
 });
}
function startSpot(){cancel();found=new Set();hinted=new Set();$('review').hidden=true;$('success').hidden=true;$('retry').hidden=true;$('hint').hidden=true;$('pair').hidden=false;const level=Number($('level').value);if(level<=2){phase='spot';drawScenes();state(`《${scene().title}》：點原圖或右圖中有變化嘅物件。`);$('hint').hidden=false;}else{phase='observe';drawScenes();$('start').disabled=true;const seconds=[0,0,12,8,5][level-1],g=generation;state(`《${scene().title}》：觀察原圖 ${seconds} 秒，之後原圖會收起。`);timer=setTimeout(()=>{if(g!==generation)return;phase='spot';drawScenes(true);$('start').disabled=false;$('hint').hidden=false;state('原圖收起咗，右圖邊啲物件變咗？');},seconds*1000);}}
function start(){cancel();$('start').disabled=false;$('success').hidden=true;$('round').textContent=`第 ${round} 關`;if(type==='differences'){startSpot();return;}puzzle=Array.from({length:cfg().n},()=>Math.floor(Math.random()*tokens.length));times=puzzle.map(()=>pick(cfg().t));observe();}
$('title').textContent=names[type];document.title=names[type]+' · Valerie&Hilary冒險樂園';$('board').classList.add(type);if(type!=='differences')$('board').style.background=`linear-gradient(#ffffff40,#ffffff70),url('assets/adventure/scene-${{train:'12',candy:'07',animals:'06'}[type]}.png') center/cover`;$('sound').textContent='♫ 音樂：開';$('sound').setAttribute('aria-pressed','true');note();
if(type==='differences'){ $('board').hidden=true;$('scenePicker').hidden=D.scenes.length===1;D.scenes.forEach((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${i+1}. ${s.title}`;$('scenePicker').append(o);});$('scenePicker').onchange=()=>{sceneIndex=Number($('scenePicker').value);round=sceneIndex+1;start();};drawScenes(); }else{puzzle=Array(cfg().n).fill(0);draw(Array(cfg().n).fill(null));}
$('start').onclick=()=>{startMusic();start();};$('level').onchange=()=>{note();start();};$('check').onclick=check;$('retry').onclick=()=>type==='differences'?startSpot():observe();$('undo').onclick=()=>{if(phase!=='answer')return;answers.pop();draw(puzzle.map((_,i)=>answers[i]??null));$('check').disabled=true;$('undo').disabled=!answers.length;state(`已填 ${answers.length}／${puzzle.length} 格`);};
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=`♫ 音樂：${sound?'開':'關'}`;$('sound').setAttribute('aria-pressed',String(sound));if(sound)startMusic();else{stopMusic();audio?.suspend().catch(()=>{});}};
$('next').onclick=()=>{if(phase!=='won')return;round++;if(type==='differences'){sceneIndex=(sceneIndex+1)%D.scenes.length;$('scenePicker').value=sceneIndex;}start();};$('closeWin').onclick=()=>{$('success').hidden=true;focusBeforeWin?.focus();$('retry').hidden=false;state('已過關！按「下一關」繼續。');$('review').hidden=false;const b=document.createElement('button');b.className='primary';b.textContent='下一關 →';b.onclick=()=>{$('next').click();};if(type==='differences')$('review').replaceChildren();$('review').append(b);};
$('hint').onclick=()=>{if(phase!=='spot')return;const n=differenceCount(),j=scene().items.findIndex((_,i)=>i<n&&!found.has(i));if(j<0)return;hinted.add(j);found.add(j);drawScenes(Number($('level').value)>=3);state(`提示：${scene().items[j].name}有變化！已找到 ${found.size}／${n} 處。`);if(found.size===n)win();};
document.addEventListener('keydown',e=>{if($('success').hidden)return;if(e.key==='Escape')$('closeWin').click();if(e.key==='Tab'){e.preventDefault();(document.activeElement===$('next')?$('closeWin'):$('next')).focus();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopMusic();audio?.suspend().catch(()=>{});if(phase==='observe'){cancel();phase='paused';$('start').disabled=false;state('遊戲已暫停，按「再試同一題」重新觀察。');$('retry').hidden=false;}}else if(sound)startMusic();});window.addEventListener('pagehide',()=>{cancel();stopMusic();audio?.suspend().catch(()=>{});});
})();
